### ISSUE TITLE
Exception handling for notifications

### ISSUE THREAD

**Issue by Neiby** [skinwalker-ranch-insiders/reapr#4]
There needs to be better exception handling in the case of urgent notifications that require acknowledgment to the reporter.
Perhaps instead of a simplified "thumbs up"-style acknowledgment, a more complete response to the reporter is required. 
This would be especially helpful in the most severe cases where the reporter might feel compelled to report elsewhere,
outside of the function where it can be controlled by the app owner. 

Another developer on the project has all the screenshots of the issue if you need them.

**Comment by rkdavies** [comment]
It's been taken care of.
